### PR TITLE
hotfix: bump api

### PR DESCRIPTION
**Pull request by LeeChristmas93**
bump deprecated api version from 1.1 to 1.2

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@mykle1 Any progress on this one? Currently our plugin does not work because of deprecated API.
Any chance you might merge this PR?

**Comment by mykle1** [comment]
I am sorry guys. I haven't looked in here for a while. I assumed that no one was using this module but I am please to see that someone is. I will merge the pull request now

**Comment by marcobiedermann** [comment]
@mykle1 Awesome, thanks for your quick reply! 👍

**Comment by mykle1** [comment]
Well, I merged the PR but now the module fails. I didn't look at the edit so I don't know what was done. I'll have to look at the data from the API and see what is going on

**Comment by marcobiedermann** [comment]
@mykle1 
It is working for me:

image

**Comment by mykle1** [comment]
well that is odd. I downloaded it after the PR and it fails. Ok, so the problem is on my end. Please enjoy the module

**Comment by marcobiedermann** [comment]
I am getting:
image

But this is because the latest entry does not have any missions included:

```json

      "id": 1414,
      "name": "Long March 3B / YZ-1 | Beidou-3 M3 & Beidou-3 M4",
      "windowstart": "December 5, 2017 00:00:00 UTC",
      "windowend": "December 5, 2017 00:00:00 UTC",
      "net": "December 5, 2017 00:00:00 UTC",
      "wsstamp": 0,
      "westamp": 0,
      "netstamp": 0,
      "isostart": "20171205T000000Z",
      "isoend": "20171205T000000Z",
      "isonet": "20171205T000000Z",
      "status": 2,
      "inhold": 0,
      "tbdtime": 1,
      "vidURLs": [
        
      ],
      "vidURL": null,
      "infoURLs": [
        
      ],
      "infoURL": null,
      "holdreason": null,
      "failreason": null,
      "tbddate": 1,
      "probability": -1,
      "hashtag": null,
      "location": {
        "pads": [
          {
            "id": 147,
            "name": "Unknown, Xichang Satellite Launch Center",
            "infoURL": "Unknown",
            "wikiURL": "https://en.wikipedia.org/wiki/Xichang_Satellite_Launch_Center",
            "mapURL": "https://www.google.com/maps?ll=28.246017,102.026556&q=28.246017,102.026556&hl=en&t=m&z=15",
            "latitude": 28.246017,
            "longitude": 102.026556,
            "agencies": [
              {
                "id": 17,
                "name": "China National Space Administration",
                "abbrev": "CNSA",
                "countryCode": "CHN",
                "type": 1,
                "infoURL": "http://www.cnsa.gov.cn/",
                "wikiURL": "http://en.wikipedia.org/wiki/China_National_Space_Administration",
                "infoURLs": [
                  "http://www.cnsa.gov.cn/"
                ]
              }
            ]
          }
        ],
        "id": 25,
        "name": "Xichang Satellite Launch Center, People's Republic of China",
        "infoURL": "",
        "wikiURL": "",
        "countryCode": "CHN"
      },
      "rocket": {
        "id": 89,
        "name": "Long March 3B / YZ-1",
        "configuration": "B / YZ-1",
        "familyname": "Long March 3",
        "agencies": [
          {
            "id": 88,
            "name": "China Aerospace Science and Technology Corporation",
            "abbrev": "CASC",
            "countryCode": "CHN",
            "type": 1,
            "infoURL": "http://www.cast.cn/item/list.asp?id=1561",
            "wikiURL": "https://en.wikipedia.org/wiki/China_Aerospace_Science_and_Technology_Corporation",
            "infoURLs": [
              "http://www.cast.cn/item/list.asp?id=1561"
            ]
          }
        ],
        "wikiURL": "https://en.wikipedia.org/wiki/Long_March_3B",
        "infoURLs": [
          
        ],
        "imageURL": "https://s3.amazonaws.com/launchlibrary/RocketImages/placeholder_1920.png",
        "imageSizes": [
          320,
          480,
          640,
          720,
          768,
          800,
          960,
          1024,
          1080,
          1280,
          1440,
          1920
        ]
      },
      "missions": [
        
      ]
    },
```

This is an issue but not related to the topic

**Comment by mykle1** [comment]
Ahh, I see. Ok, I can fix that at another time as long as the module is working for you

**Pull request merged**
